SHELL = /bin/sh

all: 

wquizchooser:
	$(MAKE) -C .. wquizchooser

clean:
	-rm -f *.or *.o *.ow *.old
	-rm -f *.rc
	-rm -f COPYING.txt COPYING.de.txt

distclean: clean
	-rm -f akfquiz.iss

new: distclean
