.\" Process this file with
.\" groff -man -Tlatin1 akfquiz.5
.\"
.TH "quizstat" 1 "4.4.0" AKFQuiz

.SH NAME
quizstat \- get some statistics about an AKFQuiz file

.SH SYNTAX
.BI "quizstat " "[ [path/]files ]"

.SH DESCRIPTION

The script 
.I quizstat
shows some statistics about
.I akfquiz
files. Unlike the other AKFQuiz-programs the file is not searched for.

With no filename,
.I quizstat
reads from standard input.

With more than one filename, or if you use wildcards
.I quizstat
summerizes all the content as if it were one file.

If you want to see the output for each file separately, use something 
like this:

.RS
for i in *.akfquiz; do echo; echo $i; quizstat $i; done
.RE

.SH LICENSE

Copyright \(co 2003-2006,2007 Andreas K. Foerster

AKFQuiz is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

AKFQuiz is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.


.SH INTERNET

http://akfquiz.nongnu.org/

.SH "SEE ALSO"
.BR akfquiz (5)
.BR scrquiz (1)
.BR grquiz (1)
.BR mkquiz (1)
.BR cgiquiz (8)
.BR linequiz (1)
