{ Information for quizhg.ppm }

const 
  marginTop    = 120;
  marginBottom = 40;
  marginLeft   = 40;
  marginRight  = 40;

{ coordinates where to get the textcolor and backgroundcolor }
const
  TextColorX = 218;
  TextColorY = 465;
  BackColorX = 83;
  BackColorY = 122;

const useTextArea = true;

{ changing this needs also changes in clgrph.pas }
const
  ScreenWidth  = 640;
  ScreenHeight = 480;
  ScreenDepth  = 16;
