.\" Process this file with
.\" groff -man -Tlatin1 akfquiz.5
.\"
.TH "quizstat" 1 "4.5.0" AKFQuiz

.SH NAME
quizstat \- statistische Daten über AKFQuiz-Dateien anzeigen

.SH SYNTAX
.BI "quizstat " "[ [Pfad/]Dateien ]"

.SH BESCHREIBUNG

Das Skript 
.I quizstat
zeigt einige statistische Daten über
.IR AKFQuiz -Dateien
an. 
Im Gegensatz zu den anderen AKFQuiz Programmen werden die Dateien nicht 
gesucht, sondern müssen mit vollständigen Pfad angegeben werden.

Wird kein Dateiname angegeben, liest
.I quizstat
von der Standardeingabe.

Wird mehr als ein Dateiname angegeben, oder werden Wildcards benutzt,
gibt
.I quizstat
die Summe von allen Dateien aus, als wären sie eine.

Wenn man die Angaben zu jeder Datei einzeln haben will, kann man etwas 
wie das folgende verwenden:

.RS
for i in *.akfquiz; do echo; echo $i; quizstat $i; done
.RE

.SH LIZENZ

Copyright \(co 2003-2006,2007 Andreas K. Förster

AKFQuiz ist Freie Software. Sie können es unter den
Bedingungen der GNU General Public License, wie von der Free
Software Foundation veröffentlicht, weitergeben und/oder
modifizieren, entweder gemäß Version 3 der Lizenz oder (nach
Ihrer Option) jeder späteren Version.

Die Veröffentlichung von AKFQuiz erfolgt in der Hoffnung, dass
es Ihnen von Nutzen sein wird, aber
.B ohne irgendeine Garantie,
sogar ohne die implizite Garantie der
.B Marktreife
oder der
.B Verwendbarkeit für einen bestimmten Zweck.

.SH INTERNET

http://akfquiz.nongnu.org/

.SH "SIEHE AUCH"
.BR akfquiz (5)
.BR scrquiz (1)
.BR grquiz (1)
.BR mkquiz (1)
.BR cgiquiz (8)
.BR linequiz (1)
